# coding: utf-8

"""
    Buses API

    Manage buses in the system  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: daniel.thom@gmail.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.admins_api import AdminsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestAdminsApi(unittest.TestCase):
    """AdminsApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.admins_api.AdminsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_add_bus(self):
        """Test case for add_bus

        adds a bus to the system  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
