# coding: utf-8

"""
    Buses API

    Manage buses in the system  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: daniel.thom@gmail.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.bus import Bus  # noqa: E501
from swagger_client.rest import ApiException


class TestBus(unittest.TestCase):
    """Bus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBus(self):
        """Test Bus"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.bus.Bus()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
