# coding: utf-8

# flake8: noqa
"""
    Buses API

    Manage buses in the system  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: daniel.thom@gmail.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

# import models into model package
from swagger_client.models.bus import Bus
